services:
  - type: web
    name: pen-shield
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: JWT_SECRET_KEY
        value: super-secret
      - key: DATABASE_URL
        value: sqlite:///instance/users.db
      - key: FRONTEND_URL
        value: https://pen-shield.onrender.com
      - key: PORT
        value: 5000
